use_frameworks!

platform :ios, '9.0'

target 'TextFieldFormatter_Example' do
  pod 'TextFieldFormatter', :path => '../'

  target 'TextFieldFormatter_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
